### PR TITLE
Support Launch At Login

### PR DESCRIPTION
**Pull request by qiuyuzhou**
其他修改:

  多个依赖库通过 cocoapod 引入。避免因为内置的版本过老，在新的环境下编译不过的问题。

### CODE REVIEW

**Comment by sm0lkk** [comment]
给个IOS没越狱可翻墙的软件吧，我找了半天没找到，谢谢了!

**Comment by UltCombo** [comment]
👍 I would love this feature.

Has there been any progress on this feature or are there issues blocking this PR?

**Comment by qiuyuzhou** [comment]
@UltCombo There is no maintaining here. 
Try this https://github.com/qiuyuzhou/ShadowsocksX-NG

**Comment by UltCombo** [comment]
Thanks!

**Pull request closed without merging**
